name = "GeoJSON"
uuid = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
license = "MIT"
version = "0.5.0"

[deps]
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
GeoInterface = "0.4, 0.5"
JSON3 = "0.1.5, 1.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
